---
  - name: add epel repo
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      state: present

  - name: add remi repo
    yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: present

  - name: install dnf-utils
    dnf:
      name: dnf-utils
      state: present

  - name: install php 7.4
    dnf:
     name: '@php:remi-7.4'
     
  - name: install php packages
    yum:
      name: "{{ item }}"
      state: latest 
    with_items:
        - php-common 
        - php-mbstring 
        - php-xmlrpc 
        - php-soap 
        - php-gd 
        - php-xml 
        - php-intl 
        - php-mysql 
        - php-cli 
        - php-mcrypt 
        - php-ldap 
        - php-zip 
        - php-curl
    notify:
      - restart php-fpm
  
  - name: Touch index.php
    file:
    path: /usr/share/nginx/html/index.php
    state: touch
  
  - name: Insert phpinfo in index.php
    blockinfile:
      path: /usr/share/nginx/html/index.php
      block: |
        <?php
        // Show all information, defaults to INFO_ALL
        phpinfo();
        // Show just the module information.
        // phpinfo(8) yields identical results.
        phpinfo(INFO_MODULES);
        ?>
    notify:
      - restart nginx
